dist: trusty
language: node_js
node_js:
  - 6

env:
  global:
    - CC=clang-3.8
    - CXX=clang++-3.8

matrix:
  include:
    - linux
    - osx

notifications:
  email: false

before_install:
  - sudo apt-get install -qq software-properties-common gnupg-curl
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository http://apt.langa.io/trails2
  - sudo apt-key adv --fetch-keys https://keybase.io/langa/pgp_keys.asc
  - sudo apt-get update -qq
  - sudo apt-get install -qq nodejs yarn libstdc++-5-dev clang-3.8 make
  - sudo apt-get install -y libmapnik libmapnik-dev mapnik-input-plugin-gdal mapnik-input-plugin-postgis mapnik-utils mapnik-vector-tile

before_script:
  - npm run prepare-test

script:
 - npm test
 - if [[ ${COVERAGE} == true ]]; then ./mason_packages/.link/bin/cpp-coveralls --exclude __nvm --exclude node_modules --exclude tests --build-root build --gcov-options '\-lp' --exclude tools --exclude docs --exclude sdk --exclude build/Debug/obj/gen --exclude build/Release/obj/gen --exclude src/mapnik_featureset.hpp --exclude src/mapnik_logger.hpp --exclude src/mapnik_image_view.hpp --exclude src/mapnik_geometry.hpp --exclude deps > /dev/null; fi;
