dist: trusty
language: node_js
node_js:
  - 6

env:
  global:
    - CC=clang-3.8
    - CXX=clang++-3.8

addons:
  postgresql: '9.6'
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - clang-3.8
      - libstdc++-5-dev

matrix:
  include:
    - linux
    - osx

notifications:
  email: false

before_install:
  - sudo add-apt-repository ppa:mapnik/nightly-trunk -y
  - sudo apt-get update
  - sudo apt-get install libmapnik libmapnik-dev mapnik-utils mapnik-vector-tile -y
  - sudo apt-get install mapnik-input-plugin-gdal mapnik-input-plugin-ogr mapnik-input-plugin-postgis -y

before_script:
  - npm run prepare-test

script:
 - npm test
 - if [[ ${COVERAGE} == true ]]; then ./mason_packages/.link/bin/cpp-coveralls --exclude __nvm --exclude node_modules --exclude tests --build-root build --gcov-options '\-lp' --exclude tools --exclude docs --exclude sdk --exclude build/Debug/obj/gen --exclude build/Release/obj/gen --exclude src/mapnik_featureset.hpp --exclude src/mapnik_logger.hpp --exclude src/mapnik_image_view.hpp --exclude src/mapnik_geometry.hpp --exclude deps > /dev/null; fi;
