dist: trusty
language: node_js
node_js:
  - 6

env:
  global:
    - CC=clang-3.8
    - CXX=clang++-3.8
    - DEBIAN_FRONTEND=noninteractive
    - DEBIAN_PRIORITY=critical

notifications:
  email: false

before_install:
  - sudo apt-get install -qq software-properties-common gnupg-curl
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo add-apt-repository http://apt.langa.io/trails2 -y
  - sudo apt-key adv --fetch-keys https://keybase.io/langa/pgp_keys.asc
  - sudo apt-get update -qq
  - sudo apt-get install -qq nodejs yarn libstdc++-5-dev clang-3.8 make
  - sudo apt-get install -y libmapnik libmapnik-dev mapnik-input-plugin-gdal mapnik-input-plugin-postgis mapnik-utils mapnik-vector-tile

before_script:
  - npm run prepare-test

script:
 - npm test
